# Generated by Django 4.0.5 on 2022-06-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, verbose_name='Заголовок')),
                ('body', models.TextField(max_length=400, verbose_name='Описание')),
                ('is_important', models.BooleanField(default=False)),
            ],
        ),
    ]
