# Generated by Django 4.0.5 on 2022-06-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.SlugField(default='unnamed tag', verbose_name='Тэг'),
        ),
    ]
